dist: xenial
language: node_js

branches:
    except:
        - /^v[0-9]/

before_install:
    - npm i -g npm
    - npm i -g firebase firebase-tools
    - firebase setup:emulators:firestore

install:
    - npm --prefix=./orm ci

script:
    - npm --prefix=./orm run build
    - npm --prefix=./orm run test
    - npm --prefix=./orm run verify

deploy:
    - provider: script
      script: bash orm/deploy.sh
      skip_cleanup: true
      node_js: 10
      on:
          tags: false
          all_branches: true
