dist: xenial
language: node_js

branches:
    except:
        - /^v[0-9]/

before_install:
    - npm i -g npm
    - npm i -g firebase firebase-tools
    - if [[ $TRAVIS_BRANCH == "production" ]]; then
        firebase use production
        echo "Using production environment"
      else
        firebase use preprod
        echo "Using preprod environment"
      fi
    - firebase setup:emulators:firestore

install:
    - npm --prefix=./orm ci
    - npm --prefix=./firestore ci

script:
    - npm --prefix=./orm run build
    - npm --prefix=./orm run test
    - npm --prefix=./orm run verify
    - npm run --prefix=./firestore gen-rules
    - npm run --prefix=./firestore test

deploy:
    - provider: script
      script: bash orm/scripts/release.sh && bash -c "npx firebase deploy --only firestore"
      skip_cleanup: true
      node_js: 10
      on:
          tags: false
          all_branches: true
